config/routes.rb
Rails.application.routes.draw do
  get 'pages/aboutus'
  get 'pages/contact'

  devise_for :users, :controllers => { registrations: 'registrations' }, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }

  root :to => 'pages#home'

  get '/index' => 'pages#home'
  get '/links' => 'pages#links'
  get '/aboutus' => 'pages#aboutus'
  get '/contact' => 'pages#contact'
  get '/edit_user' => 'users#edit'
  get '/pages/display_selection' => 'pages#display_selection'
  get '/games/result' => 'games#result'
  get '/events/finishmatch' => 'events#finishmatch'

  post '/users' => 'pages#home'
  post '/edit_user' => 'users#edit'
  post '/events/:id' => 'events#finishmatch'

  resources :users
  # match 'users/:id', :to => 'users#show', :as => :profile
  # resources :edit_user

  resources :events
  resources :games
  resources :charges
  resources :chat_rooms, only: [:new, :create, :show, :index, :destroy]

  mount ActionCable.server => '/cable'

  root 'chat_rooms#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id         :integer          not null, primary key
#  date       :date
#  time       :time
#  location   :string
#  user_id    :integer
#  sherpa_id  :integer
#  game_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Event < ApplicationRecord
  belongs_to :user
  belongs_to :game
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, :set_event, only: [:show, :edit, :update, :destroy]
  set_tab :events
  set_tab :charges
  # GET /events
  # GET /events.json
  def index
    if user_signed_in? && current_user.player == true
      @events = Event.where(user_id: current_user.id)
    elsif user_signed_in? && current_user.sherpa == true
      @events = Event.where(sherpa_id: current_user.id)
      #show where current_user.id == event.sherpa_id
    end

    # @events = Event.none

    # if params[:user_id]
      # @events = Event.where(user_id: params[:user_id])
    # else
    #   @events = Event.all
    # end
    # if user_signed_in? && current_user.player == true
    #   @events = Event.first
    # else
    #   @events = Event.all
    # end
    #  Event.where(id: current_user.id)

  end

  def finishmatch
    @event = Event.where(user_id: current_user.id).last
    @event.sherpa_id = params[:sherpa_id]
    @event.save
    # Mailer code goes here - send invite to sherpa

  end

  # GET /events/1
  # GET /events/1.json
  def add_child
  end

  def show
    # set sherpa for event after user selected that sherpa
    currentd = Date.parse(@event.date.to_s)
    @match = Game.find_by(id: @event.game_id).users.find_by(sherpa: true)
    @outputname = User.find_by(id: @match.id).name
    @event.sherpa_id = @match.id
    @event.save!
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)
    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event}
      else
        format.html  { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
    # check for match with sherpa - comes here after "select sherpa clicked" on new.html.erb, goes to show.html.erb

    # @index = 0
    # @userobject = []
    # User.all.each do |user|
    #   @userobject[@index] = user
    #   @index = @index + 1
    # end

  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:date, :time, :location, :user_id, :sherpa_id, :game_id)
    end

end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<div class="defaultspacer">
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>
      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    Event Host: <strong><%= current_user.name %></strong>
    <% form.label :user_id %>
    <%= form.number_field :user_id, id: :event_user_id, value: current_user.id, class: 'display-none' %>
  </div>

  <div class="field">
    Event Game: <strong><%= params[:game_name]  %></strong>
    <%= form.number_field :game_id, id: :event_game_id, value: params[:game_id], class: 'display-none' %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date, id: :event_date %>
  </div>

  <div class="field">
    <%= form.label :time %>
    <%= form.time_select :time, id: :event_time %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location, id: :event_location, placeholder: "ex: manly" %>
  </div>

  <!-- <div class="field">
    <%= form.label :sherpa_id %>
    <%= form.number_field :sherpa_id, id: :event_sherpa_id, placeholder: "Select on next page" %>
  </div> -->

  <!-- <div class="field">
    <%= form.label :game_id %>
    <%= form.number_field :game_id, id: :event_game_id, value: params[:game_id] %>
  </div> -->

  <div class="actions">
    <%= form.submit "Select Game Sherpa", class: 'btn btn-primary' %>
  </div>
<% end %>
</div>

app/views/events/_form2.html.erb
<div class="defaultspacer">
<%# <%= form_with(model: event, local: true) do |form| %>
<%# <% form_for( @event, :html => { :multipart => true }) do |form | %>

<%= form_for @event, url: {action: "update"}, html: {class: "nifty_form"} do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>
      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    Event Host: <strong><%= current_user.name %></strong>
    <% form.label :user_id %>
    <%= form.number_field :user_id, id: :event_user_id, value: current_user.id, class: 'display-none' %>
  </div>

  <div class="field">
    Event Game: <strong><%= params[:game_name]  %></strong>
  </div>

  <!-- <div class="field">
    Event Game: <strong> <%= params[:game_name] %> </strong>
    <% form.label :game_id %>
    <%= form.number_field :game_id, id: :event_game_id, value: params[:game_id], class: 'display-none' %>
  </div> -->

  <%# <div class="field">
    <%= form.label :sherpa_id %>
    <%# <%= form.number_field :sherpa_id, id: :sherpa_id, placeholder: "Pass in here" %>

  <%# <div class="actions">
    <%= form.submit "Select Game Sherpa", class: 'btn btn-primary' %>
  <%# </div> %>
<% end %>

<%= form_tag do %>

  <fieldset>
    <%= label_tag = "If you would like a different Sherpa select below:" %>
    <br />

<!-- TO DO
- match on location, availability (implement calendar selection screen)
- fix broken routing from here
 -->

    <% @sherpalist = User.where(sherpa: true).where.not(name: nil) %>
    <%= select_tag :sherpa_id, options_for_select(@sherpalist.pluck(:name, :id)), :include_blank => true %>

  </fieldset>
  <br />
  <div class="form-group">
    <label></label>
    <%= submit_tag nil, :class => 'btn btn-info'  %>
  </div>

<% end %>

</div>

app/views/events/edit.html.erb
<div class="defaultspacer">

<div class="jumbotron text-center">
<h1>Edit Your Event</h1>
</div>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

</div>

app/views/events/finishmatch.html.erb
<div class="defaultspacer">
<p>We will invite your sherpa to sherpa your event.</p>
<p>We will email you when s/he accepts/declines.</p>
</div>

app/views/events/index.html.erb
<div class="defaultspacer">
<p id="notice"><%= notice %></p>

<div class="jumbotron text-center">
<% if user_signed_in? && current_user.player == true %>
  <%= image_tag("myevents.png", :class => "img-fluid ")%>
<% elsif user_signed_in? && current_user.sherpa == true %>
  <h2><%= current_user.name %> you are sherpaing the following events:</h2>
  <% end %>
</div>

<table class="table table-hover">

  <thead>
    <tr>
      <th>Game</th>
      <th>Date</th>
      <th>Time</th>
      <th>Location</th>
      <th>Host</th>
      <th>Sherpa</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.game.name %></td>
        <td><%= event.date.strftime('%m/%d/%y') %></td>
        <td><%= event.time.strftime('%I:%M %P') %></td>
        <td><%= event.location %></td>
        <td><%= event.user.name %></td>

        <td>
          <% if event.sherpa_id != nil %>
            <%= User.find_by(id: event.sherpa_id).name %>
          <%end>%>
        </td>

        <% if user_signed_in? && current_user.player == true %>
         <td><% link_to 'Pay', new_charge_path %></td>
        <% end %>

        <td><%= link_to 'Chat', new_chat_room_path %></td>
        <td><%= link_to 'Details', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Cancel', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<div>
  <% if user_signed_in? && current_user.player == true %>
      <h3 class="create"><strong>Want to create an event?</strong> <%= link_to 'Select Your Game Here', games_path %></h3>

  <% elsif user_signed_in? && current_user.sherpa == true %>
      <h3>To host an event you must register as a player</h3>
  <% end %>
</div>

<div class="space-70"></div><div class="space-30"></div>
<!-- <div>
<h4><%= link_to 'Pay for your event', new_charge_path %></h4>
</div> -->
</div>

app/views/events/new.html.erb
<div class="defaultspacer">
<div class="jumbotron text-center">
<h1>New Event</h1>
<p>Enter time and location for your new event</p>
</div>

<%= render 'form', event: @event %>

<%= link_to 'Back', games_path %>
<div class="space-70"></div><div class="space-30"></div>
</div>

app/views/events/show.html.erb
<div class="defaultspacer">
<p id="notice"><%= notice %></p>

<div class="jumbotron text-center">
  <h1>Select your sherpa!</h1>
</div>

<!-- <div class="field">
  Event Host: <strong><%= current_user.name %></strong>
</div> -->

<h3>We recomend <strong><%= @outputname %></strong> as your Sherpa</h3>
</br>
<p>
  <strong>Date:</strong>
  <%= @event.date %>
</p>

<p>
  <strong>Time:</strong>
  <%= @event.time %>
</p>

<p>
  <strong>Location:</strong>
  <%= @event.location %>
</p>

<%= render 'form2', event: @event %>

<div class="space-70"></div><div class="space-30"></div>
</div>