config/routes.rb
Rails.application.routes.draw do
  get 'pages/aboutus'
  get 'pages/contact'

  devise_for :users, :controllers => { registrations: 'registrations' }, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }

  root :to => 'pages#home'

  get '/index' => 'pages#home'
  get '/links' => 'pages#links'
  get '/aboutus' => 'pages#aboutus'
  get '/contact' => 'pages#contact'
  get '/edit_user' => 'users#edit'
  get '/pages/display_selection' => 'pages#display_selection'
  get '/games/result' => 'games#result'
  get '/events/finishmatch' => 'events#finishmatch'

  post '/users' => 'pages#home'
  post '/edit_user' => 'users#edit'
  post '/events/:id' => 'events#finishmatch'

  resources :users
  # match 'users/:id', :to => 'users#show', :as => :profile
  # resources :edit_user

  resources :events
  resources :games
  resources :charges
  resources :chat_rooms, only: [:new, :create, :show, :index, :destroy]

  mount ActionCable.server => '/cable'

  root 'chat_rooms#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/game.rb
# == Schema Information
#
# Table name: games
#
#  id           :integer          not null, primary key
#  name         :string
#  min_players  :integer
#  max_players  :integer
#  age          :integer
#  playing_time :integer
#  category     :string
#  description  :string
#  image        :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  bggid        :integer
#

class Game < ApplicationRecord
  has_many :events
  has_and_belongs_to_many :users
  end

app/controllers/games_controller.rb
require 'jquery-rails'

class GamesController < ApplicationController
  before_action :authenticate_user!, :set_game, only: [:show, :edit, :update, :destroy]
  set_tab :games

  # GET /games
  # GET /games.json
  def index
    @games = Game.all

# Search/filter our database
    if params[:name]
      @games = Game.where(name: params[:name])
    end
  end

  # GET /games/1
  # GET /games/1.json
  def show
    # @game = Game.find_by :name => params[:name]
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  def result
    title = params[:title]
    # find the id
    info = HTTParty.get "http://www.boardgamegeek.com/xmlapi/search?search=#{title}"
      id = info["boardgames"]["boardgame"]
        if id.is_a? Array
          id = info["boardgames"]["boardgame"][0]["objectid"]
        else
          id = info["boardgames"]["boardgame"]["objectid"]
        end
    # find the info that id
    game = HTTParty.get "https://boardgamegeek.com/xmlapi/boardgame/#{ id }?&search=1"
      @name = game["boardgames"]["boardgame"]["name"]
      if @name.is_a? Array
        @name = game["boardgames"]["boardgame"]["name"][0]["__content__"]
      else
        @name = game["boardgames"]["boardgame"]["name"]["__content__"]
      end
      @image = game["boardgames"]["boardgame"]["image"]
      @description = game["boardgames"]["boardgame"]["description"]
      @min_players = game["boardgames"]["boardgame"]["minplayers"]
      @max_players= game["boardgames"]["boardgame"]["maxplayers"]
      @age = game["boardgames"]["boardgame"]["age"]
      @playing_time = game["boardgames"]["boardgame"]["playingtime"]
    # return game
    list = Game.where('boardgame.name' => @name)
      # redirect them to the show page for that boardgame so they can add that game to their shelf from there
        @game = Game.create(:name => @name, :description => @description, :min_players => @min_players, :max_players => @max_players, :age => @age, :playing_time => @playing_time, :image => @image)
    end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:name, :min_players, :max_players, :age, :playing_time, :description, :image)
    end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<div class="defaultspacer">
<%= form_with(model: game, local: true) do |form| %>
  <% if game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :game_name %>
  </div>

  <div class="field">
    <%= form.label :min_players %>
    <%= form.number_field :min_players, id: :game_min_players %>
  </div>

  <div class="field">
    <%= form.label :max_players %>
    <%= form.number_field :max_players, id: :game_max_players %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age, id: :game_age %>
  </div>

  <div class="field">
    <%= form.label :playing_time %>
    <%= form.number_field :playing_time, id: :game_playing_time %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%= form.text_field :category, id: :game_category %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :game_description %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_field :image, id: :game_image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
</div>

app/views/games/edit.html.erb
<div class="defaultspacer">
<h1>Editing Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>
</div>

app/views/games/index.html.erb
<div class="defaultspacer">
<p id="notice"><%= notice %></p>

<div class="jumbotron text-center">
<%= image_tag("MYGAMES.png", :class => "img-fluid ")%>
</div>

<div class="defaultspacer">
<div class="form-page">
<h1>Find your board game</h1>
</br>
</div>
<!-- Search/filter our database  to find a game-->

<div class="row col-sm-3">
  <h3 class>Search Existing Games</h3>
  <%= form_tag games_path, :method => 'get' do %>
    <p>
      <%= text_field_tag :name, params[:name], placeholder: 'Monopoly', class: 'form-control' %>
      <br/><br/>
      <%= submit_tag "Search", :name => nil, class: 'btn btn-default' %>
    </p>
  <% end %>
</div>

<!-- Search our API database to add a game-->
<div class="row col-sm-3">
<form action="/games/result">
  <!-- <label>Enter a board game:</label> -->
  <h3>Add a New Game</h3>
  <input class="form-control" type="text" name="title" placeholder="e.g. Settlers of Cataan" required autofocus=true></input>
      <br/><br/>
  <button class="btn btn-default">Search</button>

  <div class="stop-right-there">
    <%# flash[:notice] %>
  </div>
</form>
</div>

<div>
  <%= link_to "Clear Search", games_path, class: 'btn btn-default' %>
</div>


</div>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Min players</th>
      <th>Max players</th>
      <th>Age</th>
      <th>Playing time</th>
      <th>Category</th>
      <th>Description</th>
      <!-- <th>Image</th> -->
      <th colspan="3"></th>
    </tr>
  </thead>


  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.name %></td>
        <td><%= game.min_players %></td>
        <td><%= game.max_players %></td>
        <td><%= game.age %></td>
        <td><%= game.playing_time %></td>
        <td><%= game.category %></td>
        <td><%= game.description.html_safe %></td>
        <% if game.image.present? %>
        <td><%= image_tag game.image, :alt => game.name, :class => 'thumb' %></td>
        <% else %>
        <td><%= game.name %></td>
        <% end %>
        <% if user_signed_in? && current_user.player == true %>
          <td><%= link_to 'Select', game, class: 'btn btn-primary' %></td>
        <% end %>
        <!-- <td><%= link_to 'Edit', edit_game_path(game) %></td> -->
        <td><%= link_to 'Chat Room', new_chat_room_path %></td>
        <!-- <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>


<br>
<div class="space-70"></div><div class="space-30"></div>
<!-- <%= link_to 'New Game', new_game_path %> -->

</div>

app/views/games/new.html.erb
<div class="defaultspacer">
<h1>New Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Back', games_path %>
<div class="space-70"></div><div class="space-30"></div>
</div>

app/views/games/result.html.erb
<div class="search-results">
  <h2>Top hit:</h2>
  <div class="flex-row">
      <div class="details search-results">
        <h1><%= @name %></h1>
        <h2><%= @description %></h2>
        <h2><%= @min_players %></h2>
        <h2><%= @max_players %></h2>
        <h2><%= @age %></h2>
        <h2><%= @playing_time %></h2>
        <h2><img src="<%= @image %>" alt="<%= @name %>">
      </div>
  </div>
</div>

app/views/games/show.html.erb
<div class="defaultspacer">
<p id="notice"><%= notice %></p>

<div class="jumbotron text-center">
  <h1>
    <%= @game.name %>
  </h1>
</div>

<p>
  <strong>Game ID:</strong>
  <%= @game.id %>
</p>

<!-- <p>
  <strong>Name:</strong>
  <%= @game.name %>
</p> -->

<p>
  <strong>Min players:</strong>
  <%= @game.min_players %>
</p>

<p>
  <strong>Max players:</strong>
  <%= @game.max_players %>
</p>

<p>
  <strong>Age:</strong>
  <%= @game.age %>
</p>

<p>
  <strong>Playing time:</strong>
  <%= @game.playing_time %>
</p>

<p>
  <strong>Category:</strong>
  <%= @game.category %>
</p>

<p>
  <strong>Description:</strong>
  <%= @game.description.html_safe %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag @game.image, :alt => @game.name, :class => 'thumb' %>
</p>

<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>
<div>
<%= link_to 'Select This Game for Your Event', new_event_path(:game_id => @game.id, :game_name => @game.name), class: 'btn btn-primary' %>
<div class="space-70"></div><div class="space-30"></div>
</div>