config/routes.rb
Rails.application.routes.draw do
  get 'pages/aboutus'
  get 'pages/contact'

  devise_for :users, :controllers => { registrations: 'registrations' }, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }

  root :to => 'pages#home'

  get '/index' => 'pages#home'
  get '/links' => 'pages#links'
  get '/aboutus' => 'pages#aboutus'
  get '/contact' => 'pages#contact'
  get '/edit_user' => 'users#edit'
  get '/pages/display_selection' => 'pages#display_selection'
  get '/games/result' => 'games#result'
  get '/events/finishmatch' => 'events#finishmatch'

  post '/users' => 'pages#home'
  post '/edit_user' => 'users#edit'
  post '/events/:id' => 'events#finishmatch'

  resources :users
  # match 'users/:id', :to => 'users#show', :as => :profile
  # resources :edit_user

  resources :events
  resources :games
  resources :charges
  resources :chat_rooms, only: [:new, :create, :show, :index, :destroy]

  mount ActionCable.server => '/cable'

  root 'chat_rooms#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  before_action :authenticate_user!

  def new
end

def create
  # Amount in cents
  @amount = 500

  customer = Stripe::Customer.create(
    :email => params[:stripeEmail],
    :source  => params[:stripeToken]
  )

  charge = Stripe::Charge.create(
    :customer    => customer.id,
    :amount      => @amount,
    :description => 'Board Game User',
    :currency    => 'aud'
  )

rescue Stripe::CardError => e
  flash[:error] = e.message
  redirect_to new_charge_path
end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/views/charges/create.html.erb
<% if user_signed_in? && current_user.player == true %>
  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <span>Logged in as a Player: <strong><%= current_user.name || current_user.email %></strong></span>
      <%= link_to "About Us", aboutus_path, :class => 'navbar-link' %> |
      <%= link_to "Events", events_path, :class => 'navbar-link' %> |
      <%= link_to "Games", games_path, :class => 'navbar-link' %> |
      <%= link_to 'Edit Account', edit_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to 'Contact', contact_path, :class => 'navbar-link' %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>

    </div>
  </nav>
<% end %>

<h2>Thanks, you paid <strong>$5.00</strong>!</h2>

<%= link_to "My Events", events_path %>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>

    <% if user_signed_in? && current_user.player == true %>
      <nav class="navbar">
        <div class="container-fluid">
          <span>Logged in as a Player: <strong><%= current_user.name || current_user.email %></strong></span>
          <%= link_to "About Us", aboutus_path, :class => 'navbar-link' %> |
          <%= link_to "Events", events_path, :class => 'navbar-link' %> |
          <%= link_to "Games", games_path, :class => 'navbar-link' %> |
          <%= link_to 'Edit Account', edit_user_registration_path, :class => 'navbar-link' %> |
          <%= link_to 'Contact', contact_path, :class => 'navbar-link' %> |
          <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>

        </div>
      </nav>
    <% end %>


    <label class="amount">
      <span>Amount: $5.00</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="Event Booking"
          data-amount="500"
          data-locale="auto"
          data-currency="aud"
          ></script>
<% end %>

<%= link_to "Back", :back %>